<?php

declare(strict_types=1);

namespace NativePhp\LaravelCloudDeploy\Migration\Steps;

use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Process;
use NativePhp\LaravelCloudDeploy\Migration\MigrationContext;
use NativePhp\LaravelCloudDeploy\Migration\Support\ConfigGenerator;
use NativePhp\LaravelCloudDeploy\Migration\Support\ConfigRenderer;

use function Laravel\Prompts\confirm;
use function Laravel\Prompts\select;
use function Laravel\Prompts\text;

/**
 * Writes config/cloud.php from what was found on Forge.
 */
class GenerateConfigStep extends Step
{
    public function name(): string
    {
        return 'config';
    }

    public function title(): string
    {
        return 'Write config/cloud.php';
    }

    public function explanation(): string
    {
        return 'Turn the Forge setup into a config/cloud.php for cloud:deploy: PHP version, build and deploy commands, workers, '
            .'scheduler, and the database, cache and storage the app needs. You can edit it before anything is created.';
    }

    public function runsInDryRun(): bool
    {
        return true;
    }

    public function handle(MigrationContext $context): bool
    {
        $inspection = $context->inspection();
        $facts = $inspection['env']['facts'] ?? [];

        $region = select(
            'Which Cloud region should the app run in?',
            ConfigGenerator::REGIONS,
            default: $context->get('plan.region') ?? ConfigGenerator::suggestRegion($inspection['server']['region'] ?? null),
        );

        $appName = text(
            'What should the application be called in Cloud?',
            default: $context->get('plan.app_name') ?? ($facts['APP_NAME'] ?? $inspection['site']['name'] ?? 'My App'),
            required: true,
        );

        $plan = ['app_name' => $appName, 'region' => $region, 'public_bucket' => false, 'private_bucket' => false];

        if (($facts['FILESYSTEM_DISK'] ?? $facts['FILESYSTEM_DRIVER'] ?? 'local') !== 's3') {
            $this->explain(
                'Cloud\'s disk is rebuilt on every deploy, so files the app stores in storage/app need a bucket.',
                'A public bucket replaces storage/app/public (the "public" disk). A private bucket becomes the default disk for everything else.',
                'The files step copies whatever is there. An unused bucket costs little but you can skip it.',
            );

            $plan['public_bucket'] = confirm('Create a public bucket for storage/app/public?', default: true);
            $plan['private_bucket'] = confirm('Create a private bucket for other files in storage/app?', default: $inspection['local_disk_usage'] !== []);
        }

        $context->put('plan', $plan);

        $php = ConfigRenderer::render(
            ConfigGenerator::generate($inspection, $plan),
            "Generated by php artisan cloud:migrate-from-forge from the Forge site {$inspection['site']['name']}.\n"
            .'Review it, then run the command again to continue. See config/cloud.php in the package for every option.'
        );

        $path = $context->path('config/cloud.php');

        if ($context->dryRun) {
            $this->explain('Dry run: this is the config/cloud.php that would be written.');
            $context->command->line($php);

            return true;
        }

        if (File::exists($path) && File::get($path) !== $php) {
            $this->showDiff($context, $path, $php);

            if (! confirm('config/cloud.php already exists. Replace it with the version above?', default: false)) {
                $keep = confirm('Keep your existing config/cloud.php and continue with it?', default: true);

                if ($keep) {
                    $this->warn('Using your existing config/cloud.php. Make sure its databases, caches and buckets match what the site needs.');
                }

                return $keep;
            }
        }

        File::ensureDirectoryExists(dirname($path));
        File::put($path, $php);

        $this->success('Wrote config/cloud.php. Have a look at it now if you want to change sizes or names.');

        if (! confirm('Continue to creating the resources in Cloud?')) {
            $context->pause = true;
        }

        return true;
    }

    protected function showDiff(MigrationContext $context, string $path, string $php): void
    {
        $temporary = tempnam(sys_get_temp_dir(), 'cloud-config-');
        File::put($temporary, $php);

        try {
            $result = Process::run(['diff', '-u', $path, $temporary]);
            $context->command->line($result->output() ?: $php);
        } finally {
            File::delete($temporary);
        }
    }
}
