<?php

declare(strict_types=1);

namespace NativePhp\LaravelCloudDeploy\Migration\Steps;

use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Process;
use NativePhp\LaravelCloudDeploy\Migration\MigrationContext;
use NativePhp\LaravelCloudDeploy\Migration\MigrationException;
use NativePhp\LaravelCloudDeploy\Migration\Support\ConfigFile;
use NativePhp\LaravelCloudDeploy\Migration\Support\ConfigGenerator;
use NativePhp\LaravelCloudDeploy\Migration\Support\ConfigRenderer;
use NativePhp\LaravelCloudDeploy\Migration\Support\EnvExpression;

use function Laravel\Prompts\confirm;
use function Laravel\Prompts\select;
use function Laravel\Prompts\text;

/**
 * Writes config/cloud.php from what was found on Forge.
 */
class GenerateConfigStep extends Step
{
    public function name(): string
    {
        return 'config';
    }

    public function title(): string
    {
        return 'Write config/cloud.php';
    }

    public function explanation(): string
    {
        return 'Turn the Forge setup into a config/cloud.php for cloud:deploy: PHP version, build and deploy commands, workers, '
            .'scheduler, and the database, cache and storage the app needs. You can edit it before anything is created.';
    }

    public function runsInDryRun(): bool
    {
        return true;
    }

    public function handle(MigrationContext $context): bool
    {
        $inspection = $context->inspection();
        $facts = $inspection['env']['facts'] ?? [];
        $repository = $inspection['site']['repository']['full_name'] ?? null;
        $existing = $repository ? $context->cloud()->findApplicationByRepository($repository) : null;

        if ($existing) {
            // Laravel's guide keeps separate Forge servers (production,
            // staging) as environments of one Cloud application.
            $appName = (string) ($existing['attributes']['name'] ?? $repository);
            $region = (string) ($existing['attributes']['region'] ?? 'us-east-2');

            $this->explain(
                "Cloud already has an application for {$repository}: \"{$appName}\" in {$region}.",
                'Sites that deploy the same repository (production, staging and so on) live as environments of one Cloud application, so this site can be added to it.',
            );

            if (! confirm("Add this site to \"{$appName}\" as a new environment?")) {
                throw new MigrationException('cloud:deploy manages one Cloud application per repository, so this site has to go into the existing one.', [
                    'Run the command again and add it as an environment, or delete the existing application in Cloud first.',
                ]);
            }

            $taken = collect($context->cloud()->all("/applications/{$existing['id']}/environments"))
                ->pluck('attributes.name')->filter()->values()->all();
        } else {
            $region = select(
                'Which Cloud region should the app run in?',
                ConfigGenerator::REGIONS,
                default: $context->get('plan.region') ?? ConfigGenerator::suggestRegion($inspection['server']['region'] ?? null),
            );

            $appName = text(
                'What should the application be called in Cloud?',
                default: $context->get('plan.app_name') ?? ($facts['APP_NAME'] ?? $inspection['site']['name'] ?? 'My App'),
                required: true,
            );

            $taken = [];
        }

        $environment = $this->askEnvironment($context, $inspection, $taken);

        $plan = [
            'app_name' => $appName,
            'region' => $region,
            'environment' => $environment,
            'public_bucket' => false,
            'private_bucket' => false,
        ];

        if (($facts['FILESYSTEM_DISK'] ?? $facts['FILESYSTEM_DRIVER'] ?? 'local') !== 's3') {
            $this->explain(
                'Cloud\'s disk is rebuilt on every deploy, so files the app stores in storage/app need a bucket.',
                'A public bucket replaces storage/app/public (the "public" disk). A private bucket becomes the default disk for everything else.',
                'The files step copies whatever is there. An unused bucket costs little but you can skip it.',
            );

            $plan['public_bucket'] = confirm('Create a public bucket for storage/app/public?', default: true);
            $plan['private_bucket'] = confirm('Create a private bucket for other files in storage/app?', default: $inspection['local_disk_usage'] !== []);
        }

        $context->put('plan', $plan);

        $generated = ConfigGenerator::generate($inspection, $plan);
        $header = "Generated by php artisan cloud:migrate-from-forge from the Forge site {$inspection['site']['name']}.\n"
            .'Review it, then run the command again to continue. See config/cloud.php in the package for every option.';
        $path = $context->path('config/cloud.php');

        if ($context->dryRun) {
            $this->explain('Dry run: this is the config/cloud.php that would be written.');
            $context->command->line(ConfigRenderer::render($generated, $header));

            return true;
        }

        $current = $this->mergeableConfig($path, $repository, $environment);

        if ($current !== null) {
            // Another environment of the same app is already configured: add
            // this one next to it instead of replacing the file.
            $php = ConfigRenderer::render(ConfigGenerator::merge($current, $generated, $environment), $header);
            $this->showDiff($context, $path, $php);

            if (! confirm("Add the \"{$environment}\" environment to config/cloud.php? Other environments stay as they are, but comments in the file aren't kept.")) {
                return false;
            }
        } else {
            $php = ConfigRenderer::render($generated, $header);

            if (File::exists($path) && File::get($path) !== $php) {
                $this->showDiff($context, $path, $php);

                if (! confirm('config/cloud.php already exists. Replace it with the version above?', default: false)) {
                    $keep = confirm('Keep your existing config/cloud.php and continue with it?', default: true);

                    if ($keep) {
                        $this->warn('Using your existing config/cloud.php. Make sure its databases, caches and buckets match what the site needs.');
                    }

                    return $keep;
                }
            }
        }

        File::ensureDirectoryExists(dirname($path));
        File::put($path, $php);

        $this->success('Wrote config/cloud.php. Have a look at it now if you want to change sizes or names.');

        if (! confirm('Continue to creating the resources in Cloud?')) {
            $context->pause = true;
        }

        return true;
    }

    protected function showDiff(MigrationContext $context, string $path, string $php): void
    {
        $temporary = tempnam(sys_get_temp_dir(), 'cloud-config-');
        File::put($temporary, $php);

        try {
            $result = Process::run(['diff', '-u', $path, $temporary]);
            $context->command->line($result->output() ?: $php);
        } finally {
            File::delete($temporary);
        }
    }

    /**
     * Ask what to call the Cloud environment this site becomes.
     *
     * @param  array<string, mixed>  $inspection
     * @param  array<int, string>  $taken  Environments the Cloud app already has
     */
    protected function askEnvironment(MigrationContext $context, array $inspection, array $taken): string
    {
        // An environment this migration already created is fine to reuse.
        $taken = array_values(array_filter($taken, fn (string $name) => $context->state->getEnvironmentId($name) === null));

        return text(
            'What should the Cloud environment be called?',
            default: $context->get('plan.environment') ?? ConfigGenerator::suggestEnvironment($inspection['site']['repository']['branch'] ?? null, $taken),
            required: true,
            validate: function (string $name) use ($taken) {
                if (! preg_match('/^[a-z0-9][a-z0-9_-]*$/i', $name)) {
                    return 'Use letters, numbers, hyphens and underscores.';
                }

                return in_array($name, $taken, true)
                    ? "The app already has a \"{$name}\" environment. Pick another name so it isn't changed."
                    : null;
            },
        );
    }

    /**
     * The existing config/cloud.php, if it's for the same repository and
     * has environments other than this one.
     *
     * @return array<string, mixed>|null
     */
    protected function mergeableConfig(string $path, ?string $repository, string $environment): ?array
    {
        if (! File::exists($path)) {
            return null;
        }

        try {
            $current = ConfigFile::load($path);
        } catch (\Throwable) {
            return null;
        }

        $currentRepository = $current['application']['repository'] ?? null;

        if ($currentRepository instanceof EnvExpression) {
            $currentRepository = env($currentRepository->key, $currentRepository->default);
        }

        $others = array_diff(array_keys($current['environments'] ?? []), [$environment]);

        return $currentRepository === $repository && $others !== [] ? $current : null;
    }
}
